/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModelSearch: typeof import('./src/components/ModelSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenBlock: typeof import('./src/components/TokenBlock.vue')['default']
    TokenizerView: typeof import('./src/components/TokenizerView.vue')['default']
  }
}
